services:
  database:
    image: mysql:lts
    container_name: flights-db-hw-3-mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./files:/var/lib/mysql-files
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: research_project_db